spring:
  profiles:
    active: open
  datasource:
    use-db: ${spring.datasource.use-db:oracle}
    mysql:
      url: jdbc:mysql://localhost:3306/test?useSSL=false&serverTimezone=Asia/Shanghai
      username: root
      password: root
      initial-size: 3
      max-active: 20
    oracle:
      url: jdbc:oracle:thin:@localhost:1521:xe
      username: scott
      password: tiger
      initial-size: 3
      max-active: 20
    gauss:
      url: jdbc:gaussdb://localhost:5432/test
      username: gauss
      password: gauss
      initial-size: 3
      max-active: 20
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
